### PR TITLE
add openmbox.net

### PR DESCRIPTION
**Pull request by Veraellyunjie**
Regarding paid tier - I am not affiliated with the company

### CODE REVIEW

**Comment by thibaultduponchelle** [comment]
I like it but not sure how much it is a Perl shop…

**Comment by thibaultduponchelle** [comment]
From https://openmbox.net/help.html

**Comment by thibaultduponchelle** [comment]
@Veraellyunjie do you have more info?

**Comment by Veraellyunjie** [comment]
> more info?

dunno tbh

emailed support for clarification, linked this page, let's wait a bit

**Comment by Veraellyunjie** [comment]
Got a reply from support. My questions were:

* how much it is a Perl shop?
* Whether there is justifiable amount/role of perl
* Is there more perl in openmbox.net?
* could you provide a link to a repo or multiple repos?

The reply, quote:

> In fact, this website is composed of a series of Perl scripts. In addition to registering and changing passwords, there are also capacity management, quota management, antispam management, etc., all of which are Perl or shell scripts. However, these scripts are quite messy and cannot form a system engineering, so they are not open source and have not been placed on GitHub. The only database used by the entire openmbox website is pure Perl, please refer to:
https://metacpan.org/dist/DB-SimpleKV
>
> Since web cgi is Perl, backend management is Perl (see help doc), and database is Perl, what reason is there to say that it is not Perl driven?

End quote

**Pull request merged**
